# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# dependency for rgdal
before_install:
  - sudo apt update
  - sudo apt-get update
  - sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libfontconfig1-dev #package units dependency

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

# Current Issue
# checking for gdal-config... no
